-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgv9ReXxhlqr5JgBVO
mLOs+QnTqwITUGM9lyTlaULwHMegCgYIKoZIzj0DAQehRANCAAS0taS+/JrNEDLO
ZfGfo+ifvlY2TYcocfPeJGvEYJI73Zd6zoRFKiZ3PdMTBW4E+nCeidGjkd7FGgmO
2Q6qBFAG
-----END PRIVATE KEY-----